server/src/server/urls.py
# -*- coding: utf-8 -*-
'''
Url patterns for UDS project (Django)
'''
from django.conf.urls import patterns, include

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()


urlpatterns = patterns('',
    (r'^', include('uds.urls')),
)

server/src/uds/admin/urls.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2012 Virtual Cable S.L.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright notice,
#      this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright notice,
#      this list of conditions and the following disclaimer in the documentation
#      and/or other materials provided with the distribution.
#    * Neither the name of Virtual Cable S.L. nor the names of its contributors
#      may be used to endorse or promote products derived from this software
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

'''
@author: Adolfo Gómez, dkmaster at dkmon dot com
'''
from __future__ import unicode_literals
from django.conf.urls import patterns

__updated__ = '2015-04-29'

urlpatterns = patterns(
    'uds.admin.views',
    (r'^$', 'index'),
    (r'^tmpl/(?P<template>[a-zA-Z0-9_-]*)$', 'tmpl'),
    (r'^sample$', 'sample'),
)

server/src/uds/dispatchers/pam/urls.py
# -*- coding: utf-8 -*-

#
# Copyright (c) 2012 Virtual Cable S.L.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright notice,
#      this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright notice,
#      this list of conditions and the following disclaimer in the documentation
#      and/or other materials provided with the distribution.
#    * Neither the name of Virtual Cable S.L. nor the names of its contributors
#      may be used to endorse or promote products derived from this software
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

'''
@author: Adolfo Gómez, dkmaster at dkmon dot com
'''
from __future__ import unicode_literals

from django.conf.urls import patterns

urlpatterns = patterns(__package__,
     (r'^pam$', 'views.pam'),
    )

server/src/uds/urls.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2012 Virtual Cable S.L.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright notice,
#      this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright notice,
#      this list of conditions and the following disclaimer in the documentation
#      and/or other materials provided with the distribution.
#    * Neither the name of Virtual Cable S.L. nor the names of its contributors
#      may be used to endorse or promote products derived from this software
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

'''
@author: Adolfo Gómez, dkmaster at dkmon dot com
'''

from django.conf.urls import patterns, include, url
from uds.core.util.modfinder import loadModulesUrls
from uds import REST

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('uds',),
}

urlpatterns = patterns(
    'uds',
    url(r'^$', 'web.views.index', name='Index'),
    (r'^login/$', 'web.views.login'),
    (r'^login/(?P<tag>.+)$', 'web.views.login'),
    (r'^logout$', 'web.views.logout'),
    # Icons
    (r'^transicon/(?P<idTrans>.+)$', 'web.views.transportIcon'),
    # Images
    (r'^srvimg/(?P<idImage>.+)$', 'web.views.serviceImage'),
    url(r'^galimg/(?P<idImage>.+)$', 'web.views.image', name='galleryImage'),
    # Error URL
    (r'^error/(?P<idError>.+)$', 'web.views.error'),
    # Transport own link processor
    url(r'^trans/(?P<idService>.+)/(?P<idTransport>.+)$', 'web.views.transportOwnLink', name='TransportOwnLink'),
    # Authenticators custom html
    (r'^customAuth/(?P<idAuth>.*)$', 'web.views.customAuth'),
    # Preferences
    (r'^prefs$', 'web.views.prefs'),
    # Change Language
    (r'^i18n/', include('django.conf.urls.i18n')),
    # Downloads
    (r'^idown/(?P<idDownload>[a-zA-Z0-9-]*)$', 'web.views.download'),
    # downloads for client
    url(r'^down$', 'web.views.client_downloads', name='ClientDownload'),
    (r'^down/(?P<os>[a-zA-Z0-9-]*)$', 'web.views.client_downloads'),
    url(r'^pluginDetection/(?P<detection>[a-zA-Z0-9-]*)$', 'web.views.plugin_detection', name='PluginDetection'),
    # Client access enabler
    url(r'^enable/(?P<idService>.+)/(?P<idTransport>.+)$', 'web.views.clientEnabler', name='ClientAccessEnabler'),

    # Releaser
    url(r'^release/(?P<idService>.+)$', 'web.views.release', name='Releaser'),

    # Custom authentication callback
    (r'^auth/(?P<authName>.+)', 'web.views.authCallback'),
    (r'^authinfo/(?P<authName>.+)', 'web.views.authInfo'),
    (r'^about', 'web.views.about'),
    # Ticket authentication
    url(r'^tkauth/(?P<ticketId>.+)$', 'web.views.ticketAuth', name='TicketAuth'),

    # REST Api
    url(r'^rest/(?P<arguments>.*)$', REST.Dispatcher.as_view(), name="REST"),

    # Web admin GUI
    (r'^adm/', include('uds.admin.urls')),

    # Files
    (r'^files/(?P<uuid>.+)', 'web.views.file_storage'),

    # Internacionalization in javascript
    # Javascript catalog
    (r'^jsi18n/(?P<lang>[a-z]*)$', 'web.views.jsCatalog', js_info_dict),

)

# Append urls from special dispatchers
urlpatterns += loadModulesUrls()

server/src/uds/models/Authenticator.py
# -*- coding: utf-8 -*-

#
# Copyright (c) 2012 Virtual Cable S.L.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright notice,
#      this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright notice,
#      this list of conditions and the following disclaimer in the documentation
#      and/or other materials provided with the distribution.
#    * Neither the name of Virtual Cable S.L. nor the names of its contributors
#      may be used to endorse or promote products derived from this software
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

'''
.. moduleauthor:: Adolfo Gómez, dkmaster at dkmon dot com
'''

from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.db.models import signals

from uds.core.util import log
from uds.core.util.State import State
from uds.models.ManagedObjectModel import ManagedObjectModel
from uds.models.Tag import TaggingMixin

from uds.models.Util import NEVER

import logging

logger = logging.getLogger(__name__)

__updated__ = '2016-02-26'

@python_2_unicode_compatible
class Authenticator(ManagedObjectModel, TaggingMixin):
    '''
    This class represents an Authenticator inside the platform.
    Sample authenticators are LDAP, Active Directory, SAML, ...
    '''
    # pylint: disable=model-missing-unicode

    priority = models.IntegerField(default=0, db_index=True)
    small_name = models.CharField(max_length=32, default='', db_index=True)

    class Meta(ManagedObjectModel.Meta):
        '''
        Meta class to declare default order
        '''
        ordering = ('name',)
        app_label = 'uds'

    def getInstance(self, values=None):
        '''
        Instantiates the object this record contains.

        Every single record of Provider model, represents an object.

        Args:
           values (list): Values to pass to constructor. If no values are specified,
                          the object is instantiated empty and them deserialized from stored data.

        Returns:
            The instance Instance of the class this provider represents

        Raises:
        '''
        from uds.core.auths import Authenticator as fakeAuth
        if self.id is None:
            return fakeAuth(self, None, values)

        auType = self.getType()
        env = self.getEnvironment()
        auth = auType(self, env, values)
        self.deserialize(auth, values)
        return auth

    def getType(self):
        '''
        Get the type of the object this record represents.

        The type is Python type, it obtains this type from ServiceProviderFactory and associated record field.

        Returns:
            The python type for this record object

        :note: We only need to get info from this, not access specific data (class specific info)
        '''
        from uds.core import auths
        return auths.factory().lookup(self.data_type)

    def getOrCreateUser(self, username, realName=None):
        '''
        Used to get or create a new user at database associated with this authenticator.

        This user has all parameter default, that are:
        * 'real_name':realName
        * 'last_access':NEVER
        * 'state':State.ACTIVE

        Args:
           username: The username to create and associate with this auhtenticator

           realName: If None, it will be the same that username. If otherwise especified, it will be the default real_name (field)

        Returns:
            True if the ip can access this Transport.

            False if the ip can't access this Transport.

            The ip check is done this way:
            * If The associated network is empty, the result is always True
            * If the associated network is not empty, and nets_positive (field) is True, the result will be True if
            the ip is contained in any subnet associated with this transport.
            * If the associated network is empty, and nets_positive (field) is False, the result will be True if
            the ip is NOT contained in ANY subnet associated with this transport.

        Raises:


        '''
        if realName is None:
            realName = username
        user, _ = self.users.get_or_create(name=username, defaults={'real_name': realName, 'last_access': NEVER, 'state': State.ACTIVE})
        if realName is not None and realName != user.real_name:
            user.real_name = realName
            user.save()

        return user

    def isValidUser(self, username, falseIfNotExists=True):
        '''
        Checks the validity of an user

        Args:
            username: Name of the user to check

            falseIfNotExists: Defaults to True. It is used so we can return a value defined by caller.

            One example of falseIfNotExists using as True is for checking that the user is active or it doesn't exists.

        Returns:
            True if it exists and is active, falseIfNotExists (param) if it doesn't exists

        This is done so we can check non existing or non blocked users (state != Active, or do not exists)
        '''
        try:
            u = self.users.get(name=username)
            return State.isActive(u.state)
        except Exception:
            return falseIfNotExists

    @staticmethod
    def all():
        '''
        Returns all authenticators ordered by priority
        '''
        return Authenticator.objects.all().order_by('priority')

    @staticmethod
    def beforeDelete(sender, **kwargs):
        '''
        Used to invoke the Service class "Destroy" before deleting it from database.

        The main purpuse of this hook is to call the "destroy" method of the object to delete and
        to clear related data of the object (environment data such as own storage, cache, etc...

        :note: If destroy raises an exception, the deletion is not taken.
        '''
        from uds.core.util.permissions import clean
        toDelete = kwargs['instance']

        logger.debug('Before delete auth {}'.format(toDelete))

        # Only tries to get instance if data is not empty
        if toDelete.data != '':
            s = toDelete.getInstance()
            s.destroy()
            s.env.clearRelatedData()

        # Clears related logs
        log.clearLogs(toDelete)

        # Clears related permissions
        clean(toDelete)

    def __str__(self):
        return u"{0} of type {1} (id:{2})".format(self.name, self.data_type, self.id)

# Connects a pre deletion signal to Authenticator
signals.pre_delete.connect(Authenticator.beforeDelete, sender=Authenticator)

server/src/uds/templates/uds/admin/tmpl/calendars.html
{% load i18n %}
<div class="row">
  <div class="col-xs-12">
    <h1>{% trans 'Calendars' %}</h1>
    <!--<ol class="breadcrumb">
      <li><a class="lnk-dashboard" href="#">Dashboard</a></li>
      <li>{% trans 'Calendars' %}</li>
    </ol>-->
  </div>
</div><!-- /.row -->
{% if messages %}
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    {% for message in messages %}
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
       {{ message }}  
    </div>
    {% endfor %} 
  </div>
</div>
{% endif %}
{% verbatim %}
<div class="row">
    <div id="{{ calendars }}" class="col-xs-12"></div>
</div>
<div id="detail-placeholder" class="row hidden">
    <div class="col-xs-12">
        <ul class="bottom_tabs nav nav-tabs">
            <li class="active"><a href="#{{ rules }}_tab" data-toggle="tab">{% endverbatim %}{% trans 'Rules' %}{% verbatim %}</a></li>
        </ul>    
        <div class="tab-content">
            <div class="tab-pane fade in active" id="{{ rules }}_tab">
                <div class="row">
                    <div class="col-xs-12" id="{{ rules }}">
                    </div>
                </div>
            </div>
        </div>        
    </div>
</div>

{% endverbatim %}

server/src/uds/templates/uds/admin/tmpl/connectivity.html
{% load i18n %}
<div class="row">
  <div class="col-xs-12">
    <h1>{% trans 'Connectivity' %}</h1>
    <!-- <ol class="breadcrumb">
      <li><a class="lnk-dashboard" href="#">Dashboard</a></li>
      <li>{% trans 'Connectivity' %}</li>
    </ol> -->
  </div>
</div><!-- /.row -->
{% if messages %}
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    {% for message in messages %}
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
       {{ message }}  
    </div>
    {% endfor %}       
  </div>
</div>
{% endif %}
{% verbatim %}
<div class="row">
    <div class="col-lg-6" id="{{ transports }}">
    </div>
    <div class="col-lg-6" id="{{ networks }}">
    </div>
</div>
<div id="detail-placeholder" class="row hidden">
    <div class="col-xs-12">
        <ul class="bottom_tabs nav nav-tabs">
            <li class="active"><a href="#{{ transport_info }}" data-toggle="tab">{% endverbatim %}{% trans 'Overview' %}{% verbatim %}</a></li>
        </ul>    
        <div class="tab-content">
            <div class="tab-pane fade in active" id="{{ transport_info }}">
              <div class="row">
                <div class="col-xs-12">
                  <div class="well">
                  </div>
                </div>
              </div>              
            </div>
        </div>
    </div>
</div>
{% endverbatim %}

server/src/uds/templates/uds/admin/tmpl/new_image.html
{% load i18n html5 %}
{% image_size as size %}
<h3 class="text-center">{% trans 'Select image to upload' %}</h3>
<div class="center-block" style="width: 60%">
    <div class="form-group">
        <label for="id_image_name" class="col-sm-3 control-label" data-toggle="tooltip" data-title="{% trans 'Name of the image. If left empty, will get the filename as name'%}">{% trans 'Image name' %}</label>
        <input id="id_image_name" name="image_name" type="text" class="form-control" placeholder="{% trans 'Image name' %}" autofocus required>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label" data-toggle="tooltip" data-title="{% trans 'Name of the image. If left empty, will get the filename as name'%}">{% trans 'Image' %}</label>
        <div class="fileinput fileinput-new" data-provides="fileinput">
          <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: {{ size.0 }}px; height: {{ size.1 }}px;"></div>
          <div>
            <span class="btn btn-default btn-file">
            <span class="fileinput-new">{% trans 'Select image' %}</span>
            <span class="fileinput-exists">{% trans 'Change' %}</span>
            <input type="file" name="image_for_gallery" id="id-image_for_gallery"></span>
            <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">{% trans 'Remove' %}</a>
          </div>
        </div>
    </div>
</div>
<p class="text-center">{% trans 'accepts PNG, JPEG and GIF images' %}.
   {% trans 'Image will be resized to ' %}{{ size.0 }}x{{ size.1 }}.
   {% trans 'Max file size for uploading is 256Kb' %}</P>
</p>

server/src/uds/templates/uds/admin/tmpl/osmanagers.html
{% load i18n %}
<div class="row">
  <div class="col-xs-12">
    <h1>{% trans 'OS Managers' %}</h1>
    <!-- <ol class="breadcrumb">
      <li><a class="lnk-dashboard" href="#">Dashboard</a></li>
      <li>OS Managers</li>
    </ol> -->
  </div>
</div><!-- /.row -->
{% if messages %}
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    {% for message in messages %}
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
       {{ message }}
    </div>
    {% endfor %}
  </div>
</div>
{% endif %}
{% verbatim %}
<div class="row">
    <div class="col-xs-12" id="{{ osmanagers }}">
    </div>
</div>
<div id="detail-placeholder" class="row hidden">
    <div class="col-xs-12">
        <ul class="bottom_tabs nav nav-tabs">
            <li class="active"><a href="#{{ osmanager_info }}" data-toggle="tab">{% endverbatim %}{% trans 'Overview' %}{% verbatim %}</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade in active" id="{{ osmanager_info }}">
              <div class="row">
                <div class="col-xs-12">
                  <div class="well">
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>
{% endverbatim %}

server/src/uds/templates/uds/admin/tmpl/permissions_add.html
{% load i18n %}
{% verbatim %}
<form class="form-horizontal" role="form">
  <div class="form-group">
    <label for="id_auth_select" class="col-sm-2 control-label">{% endverbatim %}{% trans 'Authenticator' %}{% verbatim %}</label>
    <div class="col-sm-10">
      <select  id="id_auth_select" name="auth" class="selectpicker show-menu-arrow show-tick modal_field_data" data-style="btn-default" data-width="100%">
        <option value="-1"></option>
      {{# each auths }}
        <option value="{{ id }}">{{ name }}</option>
      {{/ each }}
      </select>
    </div>
  </div>

  <div class="form-group">
    <label for="id_item_select" class="col-sm-2 control-label">{{ label }}</label>
    <div class="col-sm-10">
      <select id="id_item_select" name="group" class="selectpicker show-menu-arrow show-tick modal_field_data" data-style="btn-default" data-width="100%">
      </select>
    </div>
  </div>

  <div class="form-group">
    <label for="id_perm_select" class="col-sm-2 control-label">{% endverbatim %}{% trans 'Permission' %}{% verbatim %}</label>
    <div class="col-sm-10">
      <select id="id_perm_select" name="group" class="selectpicker show-menu-arrow show-tick modal_field_data" data-style="btn-default" data-width="100%">
        <option value="1">{% endverbatim %}{% trans 'Read only' %}{% verbatim %}</option>
        <option value="2">{% endverbatim %}{% trans 'Full Access' %}{% verbatim %}</option>
      </select>
    </div>
  </div>

</form>
{% endverbatim %}

server/src/uds/templates/uds/admin/tmpl/pool_access_default.html
{% load i18n %}
{% verbatim %}
<form class="form-horizontal" role="form">
  <div class="form-group">
    <label for="id_action_select" class="col-sm-2 control-label">{% endverbatim %}{% trans 'Access action' %}{% verbatim %}</label>
    <div class="col-sm-10">
      <select  id="id_access_select" class="selectpicker show-menu-arrow show-tick modal_field_data" data-style="btn-default" data-width="100%">
        {{# each accessList }}
          <option value="{{ this }}"{{# ifequals this ../access }} selected{{/ ifequals }}>{{ this }}</option>
        {{/ each }}
      </select>
    </div>
  </div>
</form>
{% endverbatim %}

server/src/uds/templates/uds/admin/tmpl/pool_add_access.html
{% load i18n %}
{% verbatim %}
<form class="form-horizontal" role="form">
  <div class="form-group">
    <label for="id_priority" class="col-sm-2 control-label">{% endverbatim %}{% trans 'Priority' %}{% verbatim %}</label>
    <div class="col-sm-10">
      <input type="numeric" class="modal_field_data" id="id_priority" value="{{ priority }}">
    </div>
  </div>

  <div class="form-group">
  <label for="id_calendar_select" class="col-sm-2 control-label">{% endverbatim %}{% trans 'Calendar' %}{% verbatim %}</label>
    <div class="col-sm-10">
      <select  id="id_calendar_select" class="selectpicker show-menu-arrow show-tick modal_field_data" data-style="btn-default" data-width="100%">
        <option value="-1"></option>
      {{# each calendars }}
        <option value="{{ id }}"{{# ifequals id ../calendarId }} selected{{/ ifequals }}>{{ name }}</option>
      {{/ each }}
      </select>
    </div>
  </div>

  <div class="form-group">
    <label for="id_action_select" class="col-sm-2 control-label">{% endverbatim %}{% trans 'Access action' %}{% verbatim %}</label>
    <div class="col-sm-10">
      <select  id="id_access_select" class="selectpicker show-menu-arrow show-tick modal_field_data" data-style="btn-default" data-width="100%">
        {{# each accessList }}
          <option value="{{ this }}"{{# ifequals this ../access }} selected{{/ ifequals }}>{{ this }}</option>
        {{/ each }}
      </select>
    </div>
  </div>
</form>
{% endverbatim %}

server/src/uds/templates/uds/admin/tmpl/pool_add_group.html
{% load i18n %}
{% verbatim %}
<form class="form-horizontal" role="form">
  <div class="form-group">
    <label for="id_auth_select" class="col-sm-2 control-label">{% endverbatim %}{% trans 'Authenticator' %}{% verbatim %}</label>
    <div class="col-sm-10">
      <select  id="id_auth_select" name="auth" class="selectpicker show-menu-arrow show-tick modal_field_data" data-style="btn-default" data-width="100%">
        <option value="-1"></option>
      {{# each auths }}
        <option value="{{ id }}">{{ name }}</option>
      {{/ each }}
      </select>
    </div>
  </div>
  
  <div class="form-group">
    <label for="id_group_select" class="col-sm-2 control-label">{% endverbatim %}{% trans 'Group' %}{% verbatim %}</label>
    <div class="col-sm-10">
      <select id="id_group_select" name="group" class="selectpicker show-menu-arrow show-tick modal_field_data" data-style="btn-default" data-width="100%">
      </select>
    </div>
  </div>
  
</form>
{% endverbatim %}

server/src/uds/templates/uds/admin/tmpl/test.html
<div>
    <p> pepito </p>
</div>